local actions = require("config.actions")

vim.keymap.set({ "n", "i", "v" }, "<C-c>", actions.close_buffer)
vim.keymap.set({ "n", "i", "v" }, "<C-\\>", actions.pickers)
vim.keymap.set({ "n", "i", "v" }, "<C-/>", actions.explorer)
vim.keymap.set({ "n", "i", "v" }, "<C-.>", actions.files)
vim.keymap.set({ "n", "i", "v" }, "<C-,>", actions.recent)
vim.keymap.set({ "n", "i", "v" }, "<C-b>", actions.buffers)
vim.keymap.set({ "n", "i", "v" }, "<C-s>", actions.symbols)
vim.keymap.set({ "n", "i", "v" }, "<C-n>", actions.notifications)
vim.keymap.set({ "n", "i", "v" }, "<C-d>", actions.diagnostics)
vim.keymap.set({ "n", "i", "v" }, "<C-q>", actions.quickfix)
vim.keymap.set({ "n", "i", "v" }, "<C-g>", actions.git)
vim.keymap.set({ "n", "i", "v" }, "<C-h>", actions.git_file_history)
vim.keymap.set({ "n", "i", "v" }, "<C-l>", actions.format)
vim.keymap.set({ "n", "i", "v" }, "<C-f>", "/")
vim.keymap.set({ "n", "i", "v" }, "<F1>", actions.help)
vim.keymap.set({ "n", "i", "v" }, "<F2>", actions.explorer_panel)
vim.keymap.set({ "n", "i", "v" }, "<F3>", actions.search_working_directory)
vim.keymap.set({ "n", "i", "v" }, "<F15>", actions.search_git)
vim.keymap.set({ "n", "i", "v" }, "<F4>", actions.editor_menu)
vim.keymap.set({ "n", "i", "v" }, "<F5>", actions.debug_menu)
vim.keymap.set({ "n", "i", "v" }, "<F6>", actions.code_action)
vim.keymap.set({ "n", "i", "v" }, "<F18>", actions.rename)
vim.keymap.set({ "n", "i", "v" }, "<F7>", actions.definitions)
vim.keymap.set({ "n", "i", "v" }, "<F19>", actions.references)
vim.keymap.set({ "n", "i", "v" }, "<F8>", actions.dap_step_over)
vim.keymap.set({ "n", "i", "v" }, "<F32>", actions.dap_toggle_breakpoint)
vim.keymap.set({ "n", "i", "v" }, "<F9>", actions.dap_continue)
vim.keymap.set({ "n", "i", "v" }, "<F11>", actions.close_unlisted_buffers)
vim.keymap.set({ "n", "i", "v" }, "<F12>", actions.quick_menu)
vim.keymap.set({ "n" }, "<C-CR>", actions.definitions)
vim.keymap.set({ "n" }, "<S-CR>", actions.references)
vim.keymap.set({ "i" }, "<C-CR>", actions.auto_complete)
vim.keymap.set({ "n" }, "{", actions.quickfix_prev)
vim.keymap.set({ "n" }, "}", actions.quickfix_next)
